name: restaurant_dicoding_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  animated_toggle_switch: ^0.8.4
  equatable: ^2.0.7
  expandable_text: ^2.3.0
  flutter:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3
  google_fonts: ^6.2.1
  http: ^1.2.2
  json_annotation: ^4.9.0
  lottie: ^3.3.1
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.5.1
  sqflite: ^2.4.1
  workmanager: ^0.5.2
  flutter_timezone: ^4.1.0
 

dev_dependencies:
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.9.3
  mockito: ^5.4.5



flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/lottie/

